plugins {
    id "com.android.application"
}

android {
    namespace "com.weiji.app"
    compileSdk 33

    defaultConfig {
        applicationId "com.weiji.app"
        minSdk 21
        targetSdk 33
        versionCode 100
        versionName "0.1.0"
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    packaging {
        jniLibs {
            keepDebugSymbols.add("**/*.so")
            pickFirsts.add("lib/*/libc++_shared.so")
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ["libs"]
            assets.srcDirs = ["src/main/assets"]
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar", "*.aar"])
}
